TODO:
    class character (with few instances of characters and enemys)
        sanity
        backpack and items
        new characters
        statuses
    class inventory
        main hand
        sec hand
        armor

    class item
        is usable
        is wearable
        is destructable
    sub item usable:
        what happens after use:
            stat impact
            any special
        wearable:
            which slot, etc
            
    class fight
        special events
        special attacks

    all:
        add typehints
        read about passing a list into a func

    fight
    V | M | C
    V send init fight => C send init fight => M init fight | init 1st turn (return status) => C send status string => V print status string |
    V check if character is playable => C check if character is playable => M return if char_playable (y/what happened) => C if playable send menu el send what happened => V print returned str |
    if menu take input el new turn (loop reset) (if input)=> C send input => M apply input return what happened => C send what happened => V print what happened new turn (loop reset)

        add use item (special loop new func set)
    
    

    known bugs:
        add passive's to weapons (even empty)
        solved! fights dont dissappear from place
        solved! if enemy team empty fight is unexitable
        solved! if team dies player continues exploring
            Traceback (most recent call last):
      File "/home/kasper/python/tytul_roboczy/text_version.py", line 118, in <module>
        main()
      File "/home/kasper/python/tytul_roboczy/text_version.py", line 114, in main
        TextVersion()
      File "/home/kasper/python/tytul_roboczy/text_version.py", line 27, in __init__
        self.newGame()
      File "/home/kasper/python/tytul_roboczy/text_version.py", line 68, in newGame
        if not self.controler.initFight():
      File "/home/kasper/python/tytul_roboczy/controler.py", line 60, in initFight
        return self.dungeon.initFight()
      File "/home/kasper/python/tytul_roboczy/dungeon.py", line 143, in initFight
        self.team = Fight(self.team, self.enemies[self.current_room]).aftermath()
    KeyError: 'a3'

